#!/usr/bin/env ruby
# encoding: utf-8
#
# simple line filter for converting to JellyX::HI command parameters

$stdin.read.split("\n").each do |line|
  hi = line.split.inject({}) do |hash, word|
    hash.merge case word
    when /\Ahi/ then {}
    when /=/    then Hash[*word.split('=')]
    else Hash['name', word]
    end
  end

  puts 'HI %-16s %-7s %-7s %-12s%-s' % [
    hi['name'   ],
    hi['ctermfg'] || '-',
    hi['ctermbg'] || '-',
    hi['cterm'  ] || '-',
    hi['guisp'  ] && "guisp=#{hi['guisp']}"
  ]
end
